#!/usr/bin/env bash
# Install the Grok OSS CLI onto PATH as `grok-oss`.
#
# Default PROFILE=release builds an optimized binary and installs a small
# launcher on PATH that prefers the newest artifact under this repo's
# target/{debug,release}/grok-oss — so day-to-day you only need:
#
#   cargo build -p xai-grok-pager-bin --bin grok-oss
#   grok-oss --version
#
# For the fast human test loop use:
#
#   PROFILE=debug ./scripts/install-grok-oss.sh
#
# See GOBLIN.md / docs/architecture/GROK_OSS_IDENTITY_AND_DISTRIBUTION_PLAN.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
BIN_DIR="${PREFIX}/bin"
LIB_DIR="${PREFIX}/lib/grok-oss"
PRODUCT_BIN="grok-oss"
mkdir -p "$BIN_DIR" "$LIB_DIR"

export PROTOC="${PROTOC:-}"
if [[ -z "${PROTOC}" && -x /tmp/grok-goal-b582657efabf/implementer/tools/protoc/bin/protoc ]]; then
  export PROTOC=/tmp/grok-goal-b582657efabf/implementer/tools/protoc/bin/protoc
  export PATH="$(dirname "$PROTOC"):$PATH"
fi

PROFILE="${PROFILE:-release}"
echo "Building ${PRODUCT_BIN} ($PROFILE) from $ROOT ..."
cd "$ROOT"
if [[ "$PROFILE" == "release" ]]; then
  cargo build -p xai-grok-pager-bin --bin "$PRODUCT_BIN" --release
  SRC="$ROOT/target/release/$PRODUCT_BIN"
else
  cargo build -p xai-grok-pager-bin --bin "$PRODUCT_BIN"
  SRC="$ROOT/target/debug/$PRODUCT_BIN"
fi

ln -sfn "$SRC" "$LIB_DIR/${PRODUCT_BIN}-pager"
if ! ln -f "$SRC" "$LIB_DIR/${PRODUCT_BIN}-pager.bin" 2>/dev/null; then
  install -m 755 "$SRC" "$LIB_DIR/${PRODUCT_BIN}-pager.bin"
fi

cat > "$BIN_DIR/$PRODUCT_BIN" << EOF
#!/usr/bin/env bash
# Grok OSS CLI launcher (generated by scripts/install-grok-oss.sh).
# Prefers the newest binary under the clone that installed it.
set -euo pipefail
REPO="${ROOT}"
LIB="${LIB_DIR}"
PAGER="\${LIB}/${PRODUCT_BIN}-pager.bin"
CODEX_MODELS="\${LIB}/grok-oss-codex-models"

pick_newer() {
  local a="\$1" b="\$2"
  if [[ -x "\$a" && -x "\$b" ]]; then
    if [[ "\$a" -nt "\$b" ]]; then echo "\$a"; else echo "\$b"; fi
  elif [[ -x "\$a" ]]; then echo "\$a"
  elif [[ -x "\$b" ]]; then echo "\$b"
  else echo ""; fi
}

REPO_BIN="\$(pick_newer "\${REPO}/target/debug/${PRODUCT_BIN}" "\${REPO}/target/release/${PRODUCT_BIN}")"
if [[ -n "\$REPO_BIN" ]]; then
  if [[ ! -x "\$PAGER" || "\$REPO_BIN" -nt "\$PAGER" ]]; then
    PAGER="\$REPO_BIN"
  fi
fi

if [[ -x "\${REPO}/target/debug/goblin-codex-models" ]]; then
  CODEX_MODELS="\${REPO}/target/debug/goblin-codex-models"
fi
if [[ -x "\${REPO}/target/release/goblin-codex-models" ]]; then
  if [[ ! -x "\$CODEX_MODELS" || "\${REPO}/target/release/goblin-codex-models" -nt "\$CODEX_MODELS" ]]; then
    CODEX_MODELS="\${REPO}/target/release/goblin-codex-models"
  fi
fi

if [[ "\${1:-}" == "models" ]]; then
  if [[ -x "\$PAGER" ]]; then
    out="\$("\$PAGER" models 2>&1)" || true
    printf '%s\\n' "\$out"
    if ! printf '%s\\n' "\$out" | grep -q "Codex account"; then
      echo
      if [[ -x "\$CODEX_MODELS" ]]; then
        "\$CODEX_MODELS" || true
      fi
    fi
  elif [[ -x "\$CODEX_MODELS" ]]; then
    exec "\$CODEX_MODELS"
  else
    echo "${PRODUCT_BIN} models: no binary available" >&2
    exit 127
  fi
  exit 0
fi

if [[ ! -x "\$PAGER" ]]; then
  echo "${PRODUCT_BIN}: full CLI binary missing" >&2
  echo "hint: cd \$REPO && cargo build -p xai-grok-pager-bin --bin ${PRODUCT_BIN}" >&2
  echo "      or: PROFILE=debug \$REPO/scripts/install-grok-oss.sh" >&2
  exit 127
fi
exec "\$PAGER" "\$@"
EOF
chmod +x "$BIN_DIR/$PRODUCT_BIN"

# Optional alias for transition (does not replace primary product name).
if [[ ! -e "$BIN_DIR/goblin" ]]; then
  ln -sfn "$BIN_DIR/$PRODUCT_BIN" "$BIN_DIR/goblin" 2>/dev/null || true
fi

echo "Installed launcher: $BIN_DIR/$PRODUCT_BIN"
echo "Fallback binary:    $LIB_DIR/${PRODUCT_BIN}-pager.bin"
echo "Repo bindir:        $ROOT/target/{debug,release}/$PRODUCT_BIN (preferred when newer)"
"$BIN_DIR/$PRODUCT_BIN" --version 2>&1 | head -3 || true
echo
echo "Ensure $BIN_DIR is on your PATH."
echo "Dev loop: cargo build -p xai-grok-pager-bin --bin $PRODUCT_BIN && $PRODUCT_BIN --version"
echo "Product home default: ~/.grok-oss (override with GROK_OSS_HOME)"
