#!/usr/bin/env bash
# Install the goblin fork CLI onto PATH as `goblin`.
#
# Default PROFILE=release builds an optimized binary and installs a small
# launcher on PATH that prefers the newest artifact under this repo's
# target/{debug,release}/goblin — so day-to-day you only need:
#
#   cargo build -p xai-grok-pager-bin --bin goblin
#   goblin --version   # picks up target/debug without reinstall
#
# For the fast human test loop use:
#
#   PROFILE=debug ./scripts/install-goblin.sh
#
# See GOBLIN.md § "Local build & test loop".
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
BIN_DIR="${PREFIX}/bin"
LIB_DIR="${PREFIX}/lib/goblin"
mkdir -p "$BIN_DIR" "$LIB_DIR"

export PROTOC="${PROTOC:-}"
if [[ -z "${PROTOC}" && -x /tmp/grok-goal-b582657efabf/implementer/tools/protoc/bin/protoc ]]; then
  export PROTOC=/tmp/grok-goal-b582657efabf/implementer/tools/protoc/bin/protoc
  export PATH="$(dirname "$PROTOC"):$PATH"
fi

PROFILE="${PROFILE:-release}"
echo "Building goblin ($PROFILE) from $ROOT ..."
cd "$ROOT"
if [[ "$PROFILE" == "release" ]]; then
  cargo build -p xai-grok-pager-bin --bin goblin --release
  SRC="$ROOT/target/release/goblin"
else
  cargo build -p xai-grok-pager-bin --bin goblin
  SRC="$ROOT/target/debug/goblin"
fi

# Keep a fallback copy/symlink for when the repo target/ is missing.
ln -sfn "$SRC" "$LIB_DIR/goblin-pager"
# Also materialize a real file copy as backup (symlink may break if target cleaned).
# Prefer hardlink when same filesystem; fall back to copy.
if ! ln -f "$SRC" "$LIB_DIR/goblin-pager.bin" 2>/dev/null; then
  install -m 755 "$SRC" "$LIB_DIR/goblin-pager.bin"
fi

# PATH entry is a launcher that always prefers the newest in-repo build.
cat > "$BIN_DIR/goblin" << EOF
#!/usr/bin/env bash
# Goblin fork CLI launcher (generated by scripts/install-goblin.sh).
# Prefers the newest binary under the clone that installed it.
set -euo pipefail
REPO="${ROOT}"
LIB="${LIB_DIR}"
PAGER="\${LIB}/goblin-pager.bin"
CODEX_MODELS="\${LIB}/goblin-codex-models"

pick_newer() {
  local a="\$1" b="\$2"
  if [[ -x "\$a" && -x "\$b" ]]; then
    if [[ "\$a" -nt "\$b" ]]; then echo "\$a"; else echo "\$b"; fi
  elif [[ -x "\$a" ]]; then echo "\$a"
  elif [[ -x "\$b" ]]; then echo "\$b"
  else echo ""; fi
}

# Newest of debug / release under this repo (dev loop: cargo build → goblin).
REPO_BIN="\$(pick_newer "\${REPO}/target/debug/goblin" "\${REPO}/target/release/goblin")"
if [[ -n "\$REPO_BIN" ]]; then
  if [[ ! -x "\$PAGER" || "\$REPO_BIN" -nt "\$PAGER" ]]; then
    PAGER="\$REPO_BIN"
  fi
fi

if [[ -x "\${REPO}/target/debug/goblin-codex-models" ]]; then
  CODEX_MODELS="\${REPO}/target/debug/goblin-codex-models"
fi
if [[ -x "\${REPO}/target/release/goblin-codex-models" ]]; then
  if [[ ! -x "\$CODEX_MODELS" || "\${REPO}/target/release/goblin-codex-models" -nt "\$CODEX_MODELS" ]]; then
    CODEX_MODELS="\${REPO}/target/release/goblin-codex-models"
  fi
fi

if [[ "\${1:-}" == "models" ]]; then
  if [[ -x "\$PAGER" ]]; then
    out="\$("\$PAGER" models 2>&1)" || true
    printf '%s\\n' "\$out"
    if ! printf '%s\\n' "\$out" | grep -q "Codex account"; then
      echo
      if [[ -x "\$CODEX_MODELS" ]]; then
        "\$CODEX_MODELS" || true
      fi
    fi
  elif [[ -x "\$CODEX_MODELS" ]]; then
    exec "\$CODEX_MODELS"
  else
    echo "goblin models: no binary available" >&2
    exit 127
  fi
  exit 0
fi

if [[ ! -x "\$PAGER" ]]; then
  echo "goblin: full CLI binary missing" >&2
  echo "hint: cd \$REPO && cargo build -p xai-grok-pager-bin --bin goblin" >&2
  echo "      or: PROFILE=debug \$REPO/scripts/install-goblin.sh" >&2
  exit 127
fi
exec "\$PAGER" "\$@"
EOF
chmod +x "$BIN_DIR/goblin"

echo "Installed launcher: $BIN_DIR/goblin"
echo "Fallback binary:    $LIB_DIR/goblin-pager.bin"
echo "Repo bindir:        $ROOT/target/{debug,release}/goblin (preferred when newer)"
"$BIN_DIR/goblin" --version 2>&1 | head -3 || true
echo
echo "Ensure $BIN_DIR is on your PATH."
echo "Dev loop: cargo build -p xai-grok-pager-bin --bin goblin && goblin --version"
echo "Docs: GOBLIN.md § Local build & test loop"
